{{- if .Values.udpRoute.enabled -}}
{{- range .Values.udpRoute.items }}
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: {{ .name | default (include "gateway-api-routes.fullname" $) | quote }}
  labels:
    {{- include "gateway-api-routes.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .parentRefs }}
  parentRefs:
  {{- toYaml . | nindent 4 -}}
  {{- end }}
  rules:
  {{- toYaml . | nindent 4 }}
---
{{- end }}
{{- end }}
