{{- if .Values.gatewayClass.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name | default  (include "gateway-api.fullname" .) | quote }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
    {{- with .Values.gatewayClass.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gatewayClass.annotations }}
  annotations: {{ . | toYaml | nindent 6 }}
  {{- end }}
spec:
  {{- if .Values.gatewayClass.description }}
  description: {{ .Values.gatewayClass.description | quote }}
  {{- end }}
  controllerName: {{ .Values.gatewayClass.controllerName | quote }}
  {{- with .Values.gatewayClass.parametersRef }}
  parametersRef:
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
